---
title: "Data Load and Inspection"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(sf)
require(ggplot2)
require(tidyverse)
require(broom)
require(fields)
require(geoR)
require(tmap)
require(spdep)
require(sphet)
require(sp)
require(INLA)
require(gstat)
require(stringr)
```

# Load and Inspect Data

```{r}
data_dir = "./data/"
```

## Asthma Data

```{r}
files_list = list.files("./data/asthma_equity_data", pattern = ".csv", full.names = T)
dataframe_list = lapply(files_list, read.csv)
asthma_data = dataframe_list[[1]]
for (i in 2:(length(dataframe_list))) {
  asthma_data = rbind(asthma_data, dataframe_list[[i]])
}

colnames(asthma_data)
drop_indices = c(18:22, 32, 33, 34, 37, 38)
asthma_data = asthma_data[, -drop_indices]
colnames(asthma_data) <- c(
  "fips",
  "location",
  "unw_cent_long",
  "unw_cent_lat",
  "est_population",
  "non_his",
  "white",
  "black",
  "amer_indian",
  "asian",
  "hawaiian",
  "other",
  "two_or_more",
  "hispanic",
  "educated",
  "med_income",
  "below_pov",
  "high_school",
  "college",
  "labor_participation",
  "non_white",
  "redlining",
  "asthma_prev",
  "smoking_prev",
  "obesity_prev",
  "copd_prev",
  "particulate_matter",
  "housing_stress"
)
```

```{r}
asthma = as_tibble(asthma_data)
write_csv(asthma, "asthma_equity_data.csv")
```

## Places Data

```{r}
places_data = read.csv(str_c(data_dir, "dc_md_va_places_census_tract_data_2022.csv"))
colnames(places_data)
places_features = c(
  "StateAbbr",
  "StateDesc",
  "CountyName",
  "TractFIPS",
  "TotalPopulation",
  "ACCESS2_CrudePrev",
  "BINGE_CrudePrev",
  "BPHIGH_CrudePrev",
  "CANCER_CrudePrev",
  "CASTHMA_CrudePrev",
  "CHD_CrudePrev",
  "CHECKUP_CrudePrev",
  "COPD_CrudePrev",
  "CSMOKING_CrudePrev",
  "DIABETES_CrudePrev",
  "HIGHCHOL_CrudePrev",
  "LPA_CrudePrev",
  "OBESITY_CrudePrev",
  "SLEEP_CrudePrev",
  "STROKE_CrudePrev",
  "Geolocation"
  )
places_data = select(places_data, places_features)
colnames(places_data) <- c(
  "state_abbrev",
  "state_desc", 
  "county_name",
  "tract_fips",
  "total_population",
  "lack_insurence_prev",
  "binge_drinking_prev",
  "high_bp_prev",
  "cancer_prev",
  "adult_asthma_prev",
  "heart_disease_prev",
  "routine_physical_prev",
  "copd_prev",
  "smoking_prev",
  "diabetes_prev",
  "high_chol_prev",
  "physical_activity_prev",
  "adult_obesity_prev",
  "poor_sleep_prev",
  "stroke_prev",
  "geolocation"
  )
```

```{r}
places = as_tibble(places_data)
write_csv(places, "cdc_places_data.csv")
```

## SVI Data

```{r}
svi_dc = read.csv(str_c(data_dir, "dc_cdc_svi.csv"))
svi_md = read.csv(str_c(data_dir, "md_cdc_svi.csv"))
svi_va = read.csv(str_c(data_dir, "va_cdc_svi.csv"))

svi_data = rbind(svi_dc, svi_md, svi_va)

index = c(1:8, (1:158)[str_detect(colnames(svi_data), "E_")])

svi_data = svi_data[, index]
svi_data = svi_data[, -(28:36)]

colnames(svi_data)

colnames(svi_data) <- c(
  "state_fips",
  "state_name",
  "state_abbrev",
  "county_fips",
  "county_name",
  "fips",
  "location",
  "area_sqmi",
  "total_pop",
  "housing_units",
  "num_households",
  "poverty",
  "unemployment",
  "housing_cost_burden",
  "no_highschool",
  "uninsured",
  "age_over_65",
  "age_under_17",
  "disabilities",
  "single_parent",
  "limited_english",
  "minority",
  "multi_unit_housing",
  "mobile_homes",
  "crowded_housing",
  "no_vehicle",
  "group_quarters"
)
```

```{r}
svi = as_tibble(svi_data)
write_csv(svi, "cdc_svi_data.csv")
```

## EJI Data

```{r}
eji_files = list.files("./data", pattern = "eji", full.names = T)
eji_data = lapply(eji_files, read_csv, show_col_types = F)
eji_data = rbind(eji_data[[1]], eji_data[[2]], eji_data[[3]])

index = str_detect(colnames(eji_data), "EPL_|RPL_|SPL_|M_|F_", negate = T)
eji_data = eji_data[, index]

colnames(eji_data)

colnames(eji_data) <- c(
  "state_fips",
  "county_fips",
  "tract_code",
  "affgeoid",
  "fips",
  "name",
  "county",
  "state_abbrev",
  "state",
  "location",
  "total_pop",
  "daytime_pop",
  "ozone",
  "pm2.5",
  "diesel",
  "cancer_prob",
  "npl_proximity",
  "toxic_poximity",
  "tsd_proximity",
  "rmp_proximity",
  "coal_proximity",
  "lead_proximity",
  "park_proximity",
  "house_age",
  "walkability",
  "rail_proximity",
  "road_proximity",
  "airport_proximity",
  "watershed_proximity",
  "minority_per",
  "poverty200",
  "no_highschool",
  "unemployment",
  "renters",
  "housbdn",
  "uninsured",
  "no_internet",
  "age_over65",
  "age_under17",
  "disabilities",
  "limited_english",
  "mobile_homes",
  "group_quarters",
  "high_bp",
  "asthma",
  "cancer",
  "poor_mental",
  "diabetes"
)
```

```{r}
length(unique(eji_data$fips))
```


```{r}
eji = as_tibble(select(eji_data, "state_fips":"watershed_proximity")) %>%
  select(!c("state_fips", "county_fips", "tract_code", "name", "affgeoid", "county", "location"))

eji <- eji %>%
  group_by(fips) %>%
  summarize(
    # for every numeric column, take its mean (dropping NAs)
    across(
      where(is.numeric),
      ~ mean(.x, na.rm = TRUE)
    ),
    # if you have any non-numeric columns you still want to keep,
    # take the first value per group (or choose another summary fn)
    across(
      where(~ !is.numeric(.x)),
      ~ first(.x)
    ),
    .groups = "drop"
  )
  
write_csv(eji, "cdc_eji_data.csv")
```
